services:
  - type: web
    name: login-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SESSION_SECRET
        value: my-secret
